# Primeiramente vamos usar a imagem sugestiva na questao
FROM alpine:latest

# Executar algo quando o conteiner for executado , no caso esta imprimindo "Hello World!"
CMD echo "Hello World!" 

# Esse CMD padrao a ser executado quando o conteiner baseado na imagem é iniciado
#ECHO uma forma de imprimir algo na tela

#No terminal executo os seguintes comandos:

#docker build -t hello-world-image .
#para construir a imagem


#docker run hello-world-image
#para executar o conteiner